# With local deploy the auto shell cmds provide and run into shell in local pcs and host the container into the local docker desktop.

name: Spring Boot CI + Docker Local Deploy

on:
  push:
    branches:
      - feature/student-api

  pull_request:
    branches:
      - feature/student-api

jobs:

  build-and-deploy:

    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Build Maven project
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t springstudoc:latest .

      - name: Stop old container
        shell: powershell
        run: |
          docker stop springstudoc-container
        continue-on-error: true

      - name: Remove old container
        shell: powershell
        run: |
          docker rm springstudoc-container
        continue-on-error: true

      - name: Run new container
        shell: powershell
        run: |
          docker run -d `
            --name springstudoc-container `
            -p 8099:8099 `
            springstudoc:latest
      - name: Show running containers
        run: docker ps
